###
# configures server and install webapp from source
###
- include: ubuntu.yml
- include: letsencrypt.yml
- include: nginx.yml
- include: git.yml
- include: dependencies.yml
- include: wsgi.yml
- include: notify.yml