###
# configure nginx with HTTPS
###

- name: double check nginx is installed
  apt: name=nginx state=present update_cache=yes
  become: true

- name: delete symbolic linked website if necessary
  file: path=/etc/nginx/sites-enabled/default state=absent
  become: true

- name: write nginx SSL config
  template: src=nginx_ssl.conf.j2
            dest=/etc/nginx/conf.d/{{ app_name }}.conf
  become: true
  notify:
    - restart nginx