###
# Notify slack about deployment
###

- name: send Slack about deployment
  slack:
    token: "{{ slack_token }}"
    channel: "#deployments"
    username: "Give Code Website - Ansible"
    msg: "Site deployment completed!"
  delegate_to: localhost